[project]
name = "html-highlight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch==2.7.1",
    "optuna>=4.5.0",
    "scikit-learn>=1.7.1",
    "rich",
    "pytest",
    "numpy",
    "regex",
    "pydantic",
    "polars",
    "panel",
    "plotly",
    "fastapi[standard]>=0.128.0",
    "ipykernel>=7.2.0",
    "nbformat>=5.10.4",
    "mlflow>=3.9.0",
    "psutil>=7.2.2",
    "nvidia-ml-py>=13.590.48",
    "pyperclip>=1.11.0",
]


[tool.ruff]
line-length = 100


[tool.ruff.lint]
select = ["E", "F", "UP", "I", "SIM", "B"]
ignore = ["B905"]
